baseURL = "https://public.nikhil.io/stats/"
languageCode = "en-us"
title = "Statistics Notes"
theme = "book"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
    unsafe = true

[params]
    BookComments = false
    BookLogo = "logo.jpg"
    BookMenuBundle = "/menu"

[[deployment.targets]]
    URL = "s3://public.nikhil.io?region=us-east-1&prefix=stats/"
