version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout

      - run:
          name: Building
          command: hugo

      - run:
          name: Deploying
          command: hugo deploy
